server:
  port: 80
spring:
  application:
    name: blog
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
  datasource: #数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    druid:
      max-active: 10
      min-idle: 5
      max-wait: 5000
      initial-size: 5
      validation-query: select 1
      stat-view-servlet:
#        enabled: true
        #        login-username: admin
        #        login-password: admin
        #        allow:
        #        deny:
        url-pattern: "/druid/*"
      web-stat-filter:
        enabled: true
        url-pattern: "/druid/**"
  mvc:
    favicon:
      enabled: false
  mail:
    username: localhost@qq.com
    password: localhost
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
